groups:
  arm:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 25
    torque_enable: true

singles:
  gripper:
    operating_mode: pwm
    profile_type: time
    profile_velocity: 131
    profile_acceleration: 15
    torque_enable: true
    pwm_limit: 880
